[package]
name = "hubby-core"
version = "0.1.3"
authors = ["Alex Kesling <alex@kesling.co>"]
license = "Apache-2.0"
description = "Hubby lock service core functionality"

edition = "2021"
workspace = ".."
readme = "../README.md"
repository = "https://github.com/akesling/hubby"

[dependencies]
