use crate::ir::*;
fn name(s: &str) -> String {
    format!("«{s}»")
}
fn ast(e: &Expr) -> String {
    match &e.kind {
        Kind::Bool(b) => format!("(.boolean {b})"),
        Kind::UInt { bits, value } => format!("(.uint {bits} {value})"),
        Kind::Var(i) => format!("(.var {i})"),
        Kind::Not(x) => format!("(.negate {})", ast(x)),
        Kind::Binary { op, left, right } => {
            format!("(.binary .{} {} {})", op.lean(), ast(left), ast(right))
        }
        Kind::If { condition, yes, no } => {
            format!("(.ite {} {} {})", ast(condition), ast(yes), ast(no))
        }
        Kind::Let { value, body } => format!("(.letE {} {})", ast(value), ast(body)),
        Kind::Assert { condition, body } => format!("(.guard {} {})", ast(condition), ast(body)),
    }
}
fn code(e: &Expr, env: &str, fresh: &mut usize) -> String {
    *fresh += 1;
    let n = *fresh;
    match &e.kind {
        Kind::Bool(b) => format!("(.ok (.boolean {b}))"),
        Kind::UInt { bits, value } => format!("(Provium.word {bits} {value})"),
        Kind::Var(i) => format!("(Provium.get {env} {i})"),
        Kind::Not(x) => format!("(Provium.bind {} Provium.negate)", code(x, env, fresh)),
        Kind::Binary { op, left, right } => format!("(Provium.bind {} (fun a{n} => Provium.bind {} (fun b{n} => Provium.binary .{} a{n} b{n})))", code(left, env, fresh), code(right, env, fresh), op.lean()),
        Kind::If { condition, yes, no } => format!("(Provium.bind {} (fun c{n} => Provium.branch c{n} (fun _ => {}) (fun _ => {})))", code(condition, env, fresh), code(yes, env, fresh), code(no, env, fresh)),
        Kind::Let { value, body } => format!("(Provium.bind {} (fun x{n} => {}))", code(value, env, fresh), code(body, &format!("(x{n} :: {env})"), fresh)),
        Kind::Assert { condition, body } => format!("(Provium.bind {} (fun c{n} => Provium.guard c{n} (fun _ => {})))", code(condition, env, fresh), code(body, env, fresh)),
    }
}
pub fn generate(
    functions: &[Function],
    namespace: &str,
    usize_bits: u32,
    source_hash: &str,
) -> String {
    let mut out = format!("-- Generated by Provium. Do not hand-edit.\n-- Source SHA-256: {source_hash}\n-- Checked overflow; usize = {usize_bits} bits.\nimport Provium.Semantics\nset_option maxRecDepth 4096\nnamespace {namespace}\nopen Provium\n\ndef proviumUsizeBits : Nat := {usize_bits}\n\n");
    for f in functions {
        let schema = format!(
            "[{}]",
            f.parameters
                .iter()
                .map(|p| match p.ty.bits(usize_bits) {
                    None => ".boolean".into(),
                    Some(w) => format!(".uint {w}"),
                })
                .collect::<Vec<_>>()
                .join(", ")
        );
        let f_name = name(&f.name);
        let ir_name = name(&format!("{}_ir", f.name));
        let cert = name(&format!("{}_correspondence", f.name));
        out.push_str(&format!("-- Rust lines {}-{}; parameters in order: {}\ndef {ir_name} : Provium.Expr :=\n  {}\n\ndef {f_name} (env : Provium.Env) : Provium.Result :=\n  if Provium.validArgs {schema} env then\n    {}\n  else .error .input\n\ntheorem {cert} (env : Provium.Env) :\n    Provium.run {schema} {ir_name} env = {f_name} env := by\n  rfl\n\n", f.start_line, f.end_line, f.parameters.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join(", "), ast(&f.body), code(&f.body, "env", &mut 0)));
    }
    out.push_str(&format!("end {namespace}\n"));
    out
}
