import Generated
open Provium.State Provium.Imperative
namespace NodeElection

/-! Exact whole-body effects of `Node::reset_election` and `Node::follow`,
    generated by Provium's imperative backend. The receiver is a record value
    whose fields are those of `jarl::node::Node` in declaration order; each
    theorem gives the complete resulting record, so every field it does not
    name is unchanged. Fields the bodies never read may hold any value. -/

/-- The fields of `jarl::node::Node` in declaration order. -/
structure Fields where
  config : PureValue
  state : PureValue
  role : PureValue
  leader : PureValue
  «local» : PureValue
  membership : PureValue
  bootstrap : PureValue
  hooks : PureValue
  peers : PureValue
  votes : PureValue
  next : PureValue
  matched : PureValue
  outbox : PureValue
  dirty : PureValue
  log_from : PureValue
  snapshot_changed : PureValue
  elapsed : PureValue
  election_deadline : PureValue
  random : PureValue
  prevoting : PureValue
  leader_age : PureValue
  quorum_elapsed : PureValue
  active : PureValue
  extra_reply : PureValue
  request_from : PureValue

def Fields.value (n : Fields) : PureValue :=
  .record "Node" [("config", n.config), ("state", n.state), ("role", n.role), ("leader", n.leader),
    ("local", n.local), ("membership", n.membership), ("bootstrap", n.bootstrap), ("hooks", n.hooks),
    ("peers", n.peers), ("votes", n.votes), ("next", n.next), ("matched", n.matched),
    ("outbox", n.outbox), ("dirty", n.dirty), ("log_from", n.log_from),
    ("snapshot_changed", n.snapshot_changed), ("elapsed", n.elapsed),
    ("election_deadline", n.election_deadline), ("random", n.random), ("prevoting", n.prevoting),
    ("leader_age", n.leader_age), ("quorum_elapsed", n.quorum_elapsed), ("active", n.active),
    ("extra_reply", n.extra_reply), ("request_from", n.request_from)]

/-- The advanced SplitMix64 state (https://prng.di.unimi.it/splitmix64.c).
    The increment is written first: kernel reduction of `x + c` recurses on
    `c`, which for this literal would not finish. -/
def advance (random : Nat) : Nat := (0x9e3779b97f4a7c15 + random) % 2^64

/-- SplitMix64's 30/27/31 xor-shift-multiply mix of an advanced state. -/
def mix (z : Nat) : Nat :=
  let z := (0xbf58476d1ce4e5b9 * (z ^^^ (z >>> 30))) % 2^64
  let z := (0x94d049bb133111eb * (z ^^^ (z >>> 27))) % 2^64
  z ^^^ (z >>> 31)

private theorem advance_word (random : Nat) : advance random < 18446744073709551616 :=
  Nat.mod_lt _ (by decide)

private theorem wrapping_add_golden (bits : Nat) (checked : Bool) {random : Nat} (range : random < 2^64) :
    arithmetic bits checked "wrapping_add" "u64" random 11400714819323198485 =
      .ok (.number "u64" (advance random)) := by
  rw [wrapping_add_u64 range (by decide), advance]

/-- `reset_election` advances the generator, draws a deadline in
    `[ticks, 2 * ticks)` and restarts the elapsed count, for every fuel above
    the body's depth, target width and overflow profile. -/
theorem reset_election_exact (bits fuel : Nat) (checked : Bool) (n : Fields) (ticks random : Nat)
    (enough : 40 ≤ fuel)
    (ticksRead : pureField n.config "election_ticks" = some (.number "u64" ticks))
    (randomValue : n.random = .number "u64" random) (range : random < 2^64)
    (positive : 0 < ticks) (safe : ticks ≤ 2^63) :
    Jarl.node_Node_reset_election bits checked fuel n.value [] =
      .ok (.unit, { n with
        random := .number "u64" (advance random),
        election_deadline := .number "u64" (ticks + mix (advance random) % ticks),
        elapsed := .number "u64" 0 }.value) := by
  obtain ⟨fuel, rfl⟩ : ∃ f, fuel = f + 40 := ⟨fuel - 40, by omega⟩
  have ticksWord : ticks < 18446744073709551616 := by omega
  have sumWord : ∀ x, ticks + x % ticks < 18446744073709551616 := fun x => by
    have := Nat.mod_lt x positive
    omega
  simp (maxDischargeDepth := 8) [Jarl.node_Node_reset_election, Jarl.node_Node_reset_election_ir, Provium.Imperative.run, eval, Fields.value,
    randomValue, set_same, set_other, field_record, bind, Except.bind, pure, Except.pure, update, replaceField,
    binary, ticksRead, wrapping_add_golden, wrapping_mul_u64, xor_u64, shift_right_u64, rem_u64, add_u64,
    mod_word, xor_word, shift_word, range, ticksWord, sumWord, positive, mix, advance_word]

/-- `follow` steps down: Follower role, no pre-vote, the given leader, a
    restarted leader age when a leader is known, and a fresh election timer. -/
theorem follow_exact (bits fuel : Nat) (checked : Bool) (n : Fields) (leader : PureValue) (ticks random : Nat)
    (enough : 60 ≤ fuel)
    (ticksRead : pureField n.config "election_ticks" = some (.number "u64" ticks))
    (randomValue : n.random = .number "u64" random) (range : random < 2^64)
    (positive : 0 < ticks) (safe : ticks ≤ 2^63) :
    Jarl.node_Node_follow bits checked fuel n.value [leader] =
      .ok (.unit, { n with
        role := .variant "Role" "Follower" [],
        prevoting := .absent,
        leader := leader,
        leader_age := (match leader with | .present _ => .number "u64" 0 | _ => n.leader_age),
        random := .number "u64" (advance random),
        election_deadline := .number "u64" (ticks + mix (advance random) % ticks),
        elapsed := .number "u64" 0 }.value) := by
  obtain ⟨fuel, rfl⟩ : ∃ f, fuel = f + 60 := ⟨fuel - 60, by omega⟩
  have ticksWord : ticks < 18446744073709551616 := by omega
  have sumWord : ∀ x, ticks + x % ticks < 18446744073709551616 := fun x => by
    have := Nat.mod_lt x positive
    omega
  cases leader <;>
  simp (maxDischargeDepth := 8) [Jarl.node_Node_follow, Jarl.node_Node_follow_ir, Provium.Imperative.run, eval,
    Fields.value, randomValue, set_same, set_other, field_record, bind, Except.bind, pure, Except.pure, update,
    replaceField, binary, ticksRead, wrapping_add_golden, wrapping_mul_u64, xor_u64, shift_right_u64, rem_u64,
    add_u64, mod_word, xor_word, shift_word, range, ticksWord, sumWord, positive, mix, advance_word, select,
    pureMatch, List.foldlM]

end NodeElection
